# Generated by Django 4.2.3 on 2023-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_vendor'),
        ('Add_to_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='product',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
